"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Shield, Headphones, Ticket, Scale, CheckCircle2, ChevronRight, ExternalLink } from "lucide-react";
import { PublicNavbar } from "@/components/PublicNavbar";
import { PublicFooter } from "@/components/PublicFooter";

const BOTS = [
  {
    id: "support",
    name: "SyncInk Support Bot",
    icon: Shield,
    color: "text-brand-crimson",
    bgLight: "bg-brand-red/10",
    border: "border-brand-red/30",
    bgActive: "bg-brand-red/20",
    lastUpdated: "October 2026",
    sections: [
      {
        title: "1. Acceptance of Terms",
        content: "By utilizing the SyncInk Support Security Engine on the official Support Server, you agree strictly to abide by all moderation, anti-raid, and anti-nuke directives enforced by the system. Interaction with the server constitutes binding acceptance of these security operations."
      },
      {
        title: "2. User Conduct & Prohibited Activities",
        content: "Users agree to maintain high standards of digital conduct across all SyncInk platforms. You expressly agree not to:",
        points: [
          "Engage in harassment, bullying, hate speech, defamation, or discriminatory abuse against members or staff.",
          "Post, upload, stream, or distribute any NSFW, sexually explicit, gory, or illegal content.",
          "Deploy unauthorized automation, spam bots, user-bots, or raid utilities against SyncInk services.",
          "Advertise external Discord servers, commercial products, or send unsolicited DMs to server members."
        ]
      },
      {
        title: "3. Disclaimers & Limitation of Liability",
        content: "SyncInk services are provided strictly on an 'AS-IS' and 'AS-AVAILABLE' basis. While our security engines work continuously to protect server integrity, we make no warranties regarding uninterrupted availability, zero latency, or third-party Discord API outages."
      },
      {
        title: "4. Moderation Sanctions & Account Termination",
        content: "SyncInk administrators and automated security shields reserve the right, at their sole discretion, to issue warnings, timeouts, kicks, server bans, and API blacklists to any user who breaches these Terms. Serious violations result in immediate permanent bans without prior notice."
      }
    ]
  },
  {
    id: "ticket",
    name: "SyncInk Ticket Bot",
    icon: Ticket,
    color: "text-brand-purple",
    bgLight: "bg-purple-500/10",
    border: "border-purple-500/30",
    bgActive: "bg-purple-500/20",
    lastUpdated: "October 2026",
    sections: [
      {
        title: "1. Service Provision",
        content: "The SyncInk Ticket Bot is provided as an autonomous moderation and support workflow utility. By installing the bot, you grant it permission to manage roles, channels, and message transcripts within authorized categories."
      },
      {
        title: "2. Transcript Data Handling",
        content: "HTML Transcripts generated by the bot are strictly private between the server staff and the ticket creator. You agree not to distribute sensitive ticket logs to unauthorized third parties without consent. SyncInk is not responsible for data breaches resulting from misconfigured staff roles."
      },
      {
        title: "3. Acceptable Use Policy",
        content: "You may not use the ticketing infrastructure to:",
        points: [
          "Facilitate illegal transactions, scams, or malicious activities.",
          "Spam the Discord API by intentionally creating and closing tickets in rapid succession.",
          "Store illegal or highly sensitive personal information (PII, SSN, Credit Cards) within ticket logs."
        ]
      },
      {
        title: "4. Service Interruptions",
        content: "We strive for 99.9% uptime, but do not guarantee that the bot will be immune to Discord API rate limits or gateway drops. We reserve the right to suspend bot access for servers that abuse rate limits."
      }
    ]
  },
  {
    id: "voice",
    name: "SyncInk Voice Bot",
    icon: Headphones,
    color: "text-cyan-400",
    bgLight: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    bgActive: "bg-cyan-500/20",
    lastUpdated: "July 2026",
    sections: [
      {
        title: "1. Acceptance of Terms",
        content: "By inviting the Voice Bot to your Discord server and using the dynamic Join-to-Create dashboard, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not use our service."
      },
      {
        title: "2. Use of Service",
        content: "You agree to use the bot only for lawful purposes and in a way that does not infringe the rights of anyone else's use and enjoyment.",
        points: [
          "You must not use voice hubs to harass, abuse, or harm another person.",
          "You must comply with Discord's Terms of Service and Community Guidelines regarding voice channel conduct.",
          "Bypassing ghost-channel purgers or bitrate limiters through exploits is strictly forbidden."
        ]
      },
      {
        title: "3. Intellectual Property",
        content: "The 'SyncInk Voice' name, brand identity, custom dashboard design, layout, and unique interface are the exclusive intellectual property of SyncInk. Any unauthorized copying or imitation of our visual design is strictly prohibited."
      },
      {
        title: "4. Service Availability",
        content: "We strive to ensure high uptime for voice channel generators, but we do not guarantee that the service will always be available. We reserve the right to suspend or withdraw the service for maintenance without notice."
      }
    ]
  }
];

export default function UnifiedTermsPage() {
  const [activeTab, setActiveTab] = useState(BOTS[0].id);
  const activeBot = BOTS.find(b => b.id === activeTab)!;

  return (
    <div className="min-h-screen bg-[#080a0f] text-slate-100 flex flex-col selection:bg-brand-purple selection:text-white">
      <PublicNavbar />

      {/* Header Banner */}
      <section className="relative overflow-hidden pt-16 pb-12 border-b border-white/[0.08] bg-gradient-to-b from-[#111624] via-[#0b0e15] to-[#080a0f]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-950/60 border border-blue-800/50 text-blue-400 text-xs font-bold uppercase tracking-wider mb-4">
            <Scale className="h-3.5 w-3.5" />
            Unified Legal Documentation
          </div>
          <h1 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
            Terms of Service Hub
          </h1>
          <p className="mt-4 text-sm text-slate-400 max-w-2xl mx-auto">
            Select a SyncInk ecosystem bot below to view its specific operational terms, acceptable use policies, and service agreements.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex-1 w-full flex flex-col lg:flex-row gap-8">
        
        {/* Sidebar Tabs */}
        <div className="lg:w-80 flex-shrink-0">
          <div className="sticky top-24 space-y-3">
            <h2 className="text-xs font-bold text-slate-500 uppercase tracking-widest pl-2 mb-4">Select a Service</h2>
            <div className="flex flex-col gap-3">
              {BOTS.map((bot) => {
                const isActive = activeTab === bot.id;
                const Icon = bot.icon;
                return (
                  <button
                    key={bot.id}
                    onClick={() => setActiveTab(bot.id)}
                    className={`relative flex items-center gap-4 w-full p-4 rounded-2xl text-left transition-all duration-300 ${
                      isActive 
                        ? `bg-white/[0.04] border ${bot.border} shadow-lg` 
                        : 'border border-transparent hover:bg-white/[0.02] text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    {isActive && (
                      <motion.div
                        layoutId="activeTabIndicator"
                        className={`absolute inset-0 rounded-2xl border ${bot.border} bg-gradient-to-r from-transparent to-white/[0.01]`}
                        initial={false}
                        transition={{ type: "spring", stiffness: 400, damping: 30 }}
                      />
                    )}
                    <div className={`relative z-10 p-2.5 rounded-xl ${isActive ? bot.bgActive : 'bg-white/5'} ${isActive ? bot.color : 'text-slate-400'}`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <span className={`relative z-10 font-bold text-[15px] ${isActive ? 'text-white' : ''}`}>
                      {bot.name}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Dynamic Content Area */}
        <div className="flex-1 min-w-0">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.3, ease: "easeOut" }}
              className="bg-[#0e121d] border border-white/[0.08] rounded-[2rem] p-6 sm:p-10 shadow-2xl relative overflow-hidden"
            >
              {/* Background Glow */}
              <div className={`absolute top-0 right-0 w-72 h-72 rounded-full blur-[120px] pointer-events-none opacity-30 ${activeBot.bgLight}`} />

              <div className="relative z-10">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-white/[0.06] pb-6 mb-8 gap-4">
                  <div>
                    <h2 className="text-2xl sm:text-3xl font-black text-white flex items-center gap-3">
                      <activeBot.icon className={`w-7 h-7 sm:w-8 sm:h-8 ${activeBot.color}`} />
                      {activeBot.name} Terms
                    </h2>
                    <p className="text-sm text-slate-400 mt-2">
                      Please read these terms carefully before engaging with this specific bot.
                    </p>
                  </div>
                  <span className={`self-start sm:self-auto px-3 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${activeBot.border} ${activeBot.bgLight} ${activeBot.color}`}>
                    Updated {activeBot.lastUpdated}
                  </span>
                </div>

                <div className="space-y-10">
                  {activeBot.sections.map((sec, idx) => (
                    <div key={idx} className="space-y-3">
                      <h3 className="text-lg font-bold text-white flex items-center gap-2">
                        <span className={activeBot.color}>§</span> {sec.title}
                      </h3>
                      <p className="text-sm text-slate-300 leading-relaxed">
                        {sec.content}
                      </p>
                      {sec.points && (
                        <div className="mt-3 space-y-2.5 pl-2">
                          {sec.points.map((pt, pIdx) => (
                            <div key={pIdx} className="flex items-start gap-2.5 text-sm text-slate-400">
                              <CheckCircle2 className={`w-4 h-4 shrink-0 mt-0.5 ${activeBot.color}`} />
                              <span className="leading-relaxed">{pt}</span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>

      </main>
      <PublicFooter />
    </div>
  );
}
